---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: bazzite-dx-gnome
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-dx-gnome
image-version: latest

modules:
  - type: script
    snippets:
      - "mkdir /nix"
  - type: files
    files:
      - source: system
        destination: /
  - type: justfiles
    validate: true
  - type: dnf
    repos:
      copr:
        - atim/starship
    install:
      packages:
        - virt-manager
        - edk2-ovmf
        - qemu
        - git-delta
        - patch
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks
  - type: signing
  - type: dnf
    repos:
      files:
        - terra.repo
    install:
      packages:
        - zed
  - type: dnf
    repos:
      copr:
        - wezfurlong/wezterm-nightly
    install:
      packages:
        - wezterm
